# Generated by Django 5.0.4 on 2024-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('corporate', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=50)),
                ('free_time', models.DateTimeField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('image', models.ImageField(upload_to='profiles')),
            ],
        ),
    ]
