# Generated by Django 5.0.4 on 2024-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('skill', models.CharField(choices=[('marketing', 'Marketing'), ('project_management', 'Project Management'), ('customer service', 'customer service')], max_length=50)),
                ('experience', models.DateField()),
            ],
        ),
    ]
