# Generated by Django 5.0.4 on 2024-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workdemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='workdemo')),
                ('video', models.FileField(upload_to='workdemo')),
                ('file', models.FileField(upload_to='workdemo')),
            ],
        ),
    ]
