# Generated by Django 5.0.4 on 2024-04-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_workdemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.IntegerField(max_length=10),
        ),
    ]
