# Generated by Django 5.0.4 on 2024-04-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_skill_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('project_management', 'Project Management'), ('customer service', 'customer service'), ('software development', 'Software Development')], max_length=50),
        ),
    ]
