# Generated by Django 5.0.4 on 2024-04-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_skill_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='free_time',
            field=models.TimeField(),
        ),
    ]
