# Generated by Django 5.0.4 on 2024-04-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_login_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
