# Generated by Django 5.0.4 on 2024-04-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_delete_login_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exchange',
        ),
        migrations.AddField(
            model_name='profile',
            name='needed_skills',
            field=models.TextField(default='software development', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='free_time',
            field=models.IntegerField(max_length=10),
        ),
    ]
