# Generated by Django 5.0.4 on 2024-04-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_profile_exchange_profile_needed_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='free_time',
            field=models.IntegerField(),
        ),
    ]
