# Generated by Django 5.0.4 on 2024-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_profile_free_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='free_time',
            field=models.TimeField(),
        ),
    ]
