# Generated by Django 5.0.4 on 2024-05-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
