# Generated by Django 5.0.4 on 2024-05-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_workdemo_created_at_alter_workdemo_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
