# Generated by Django 5.0.4 on 2024-05-11 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_delete_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField()),
                ('screenshot', models.ImageField(upload_to='reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReportA', to=settings.AUTH_USER_MODEL)),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReportB', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
